version: "3.8"
services:
  postgres:
    image: postgres:13-alpine
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recent_contests
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./db:/var/lib/postgresql/data

  recent_contests:
    build: .
    restart: on-failure
    ports:
      - "8001:8000"
    environment:
      PYTHONPATH: "/work"
    volumes:
      - ./logs:/work/logs
    command: ./wait-for-it.sh postgres:5432 -t 120 -- uvicorn --host 0.0.0.0 main:app

  spider:
    build: .
    restart: on-failure
    environment:
      PYTHONPATH: "/work"
    volumes:
      - ./logs:/work/logs
    command: cron -L15 -f

volumes:
  db:
  logs:
