version: "3.8"
services:
  recent_contests:
    build: .
    ports:
      - "8001:8000"
    environment:
      PYTHONPATH: "/work"
    volumes:
      - db:/work/db
      - logs:/work/logs
    command: uvicorn --host 0.0.0.0 main:app

  spider:
    build: .
    environment:
      PYTHONPATH: "/work"
    volumes:
      - db:/work/db
      - logs:/work/logs
    command: cron -f

volumes:
  db:
  logs:
